### ISSUE TITLE
Become active on Github.

### ISSUE THREAD

**Issue by paaljoachim** [brewlabs/sendpress#120]
One way to create a living and breathing community is to be sure to read and respond to messages on Github to get feedback and new thoughts on adjustments that could be made.

For instance check out Ninja Forms issues section: https://github.com/wpninjas/ninja-forms/issues
They really use Github and also get feedback on adjustments.

**Comment by joshlyford** [comment]
We currently use Jira to track everything. it looks like ninja forms uses github to track items. We will review and see if making the switch is something that works for us.
