### ISSUE TITLE
A final conclusion after having sent out the first newsletter.

### ISSUE THREAD

**Issue by paaljoachim** [brewlabs/sendpress#122]
The conclusion is that going through the logic, merging specific sections on creating a newsletter/email, adjusting the user interface needs to be fixed. Fix it and your product will improve a lot.

Bottom line is that I like SendPress and I look forward to becoming a lot better.

I am also available for hire. To help with additional detailed user interface feedback, create docs, articles and videos.

**Comment by joshlyford** [comment]
Thanks for all the input. We may reach out for more help once we work through everything you added.

Josh
