### ISSUE TITLE
Melhorar edição de imagem dentro do texto

### ISSUE THREAD

**Issue by anapaulabrasa** [brewlabs/sendpress#136]
Não é possível editar imagens dentro do próprio campo de edição de texto, em Emails. Para aumentar ou diminuir uma imagem, por exemplo, é necessário deletá-la e inseri-la novamente com o tamanho correto.

**Comment by cabelotaina** [comment]
Olá Acabei de testar se existe esta funcionalidade e vi que sim, eu redimencionar o tamanho da imagem, no entanto a imagem perde qualidade, se aumentada, o que me pareceu normal.

**Comment by anapaulabrasa** [comment]
Estranho. 
A edição que estou me referindo é esta barra que aparece acima da imagem no copor de texto no primeiro print abaixo - que é numa página de edição de post. 
Perceba que no segundo print, que fiz ao editar um boletim no Jaiminho, isso não aparece.

![editarimagpost](https://cloud.githubusercontent.com/assets/2422926/13175984/ba3e06b6-d6f5-11e5-81f5-c3c0685eedac.png)

![editimagbolti](https://cloud.githubusercontent.com/assets/2422926/13175987/c16b840e-d6f5-11e5-9cd9-ec3fb8e2df4a.png)
